delimiter: str = input('Введите строку-разделитель:')
line_1: str = input("Введите первую строку: ")
line_2: str = input('Введите вторую строку: ')
line_3: str = input('Введите третью строку: ')

print(line_1, end='')
print(delimiter, end='')
print(line_2, end='')
print(delimiter, end='')
print(line_3)
